/**
 * Intrinsic pixel dimensions of every plate, generated by
 * produccion/edicion.py from the files themselves.
 *
 * Section 91 asks for proper image loading. Without width/height the
 * browser cannot reserve space, so the document reflowed as plates decoded
 * -- measured, it grew 19,488 -> 20,280px during a single scroll. Typing
 * these by hand would let them drift from the assets the pipeline cuts, so
 * they are read off the files.
 */
export const MEDIDAS: Record<string, readonly [number, number]> = {
  "/cine/a2-esmeralda.avif": [1200, 262],
  "/cine/a2-isabella.avif": [596, 842],
  "/cine/a2-raiz.avif": [1000, 812],
  "/cine/a2-vibe.avif": [385, 835],
  "/cine/a3-ingres.avif": [1200, 1020],
  "/cine/a3-lobo.avif": [613, 860],
  "/cine/a3-loreal.avif": [889, 944],
  "/cine/a4-ceguera.avif": [1400, 1400],
  "/cine/a4-pelo-plano.avif": [1500, 1500],
  "/cine/a4-pintura.avif": [1500, 1500],
  "/cine/pelo-cobre.avif": [1150, 3229],
  "/edicion/campana-marquesina-poster.avif": [1280, 1913],
  "/edicion/cap-impreso.avif": [1553, 1013],
  "/edicion/cap-marca.avif": [1680, 1260],
  "/edicion/cap-producto.avif": [1280, 796],
  "/edicion/ceguera-figura.avif": [1100, 1629],
  "/edicion/detalle-vibe.avif": [377, 542],
  "/edicion/detalle-voluntee.avif": [345, 412],
  "/edicion/hero-retablo-completo.avif": [1680, 1050],
  "/edicion/hero-retablo.avif": [1680, 1050],
  "/edicion/panel-3.avif": [580, 1010],
  "/edicion/panel-6.avif": [310, 400],
  "/edicion/panel-7.avif": [360, 470],
  "/edicion/panel-9.avif": [240, 300],
  "/edicion/plancha-vibe.avif": [428, 3012],
  "/edicion/plancha-voluntee.avif": [375, 1471],
  "/edicion/plano-i-bg.avif": [1400, 1400],
  "/edicion/plano-i-fg.avif": [1200, 1200],
  "/edicion/plano-ii-bg.avif": [454, 484],
  "/edicion/plano-ii-fg.avif": [1400, 1050],
  "/edicion/plano-iii-bg.avif": [1400, 2092],
  "/edicion/plano-iv-bg.avif": [385, 835],
  "/edicion/plano-v-bg.avif": [860, 1209],
  "/edicion/plano-v-fg.avif": [1400, 913],
  "/images/about.png": [1024, 1536],
  "/images/asset4.png": [768, 202],
  "/images/luxeestate.png": [1024, 482],
  "/images/mockupisa.png": [4500, 3000],
  "/images/mockupraiz.png": [4000, 3000],
  "/images/portafolioabierto.png": [1553, 1013],
  "/images/profilepicture.png": [832, 1248],
  "/images/vibe.png": [1512, 982],
  "/images/voluntee.png": [2162, 1204],
  "/trabajo/t-esmeralda.avif": [900, 640],
  "/trabajo/t-ilustracion.avif": [900, 640],
  "/trabajo/t-isabella.avif": [900, 640],
  "/trabajo/t-libro.avif": [900, 640],
  "/trabajo/t-lobo.avif": [900, 640],
  "/trabajo/t-nespresso.avif": [900, 640],
  "/trabajo/t-vibe.avif": [900, 640],
  "/trabajo/t-voluntee.avif": [900, 640],
};

/** Width/height props for an <img>, or nothing if the plate is unknown. */
export function medidas(src: string) {
  const m = MEDIDAS[src];
  return m ? { width: m[0], height: m[1] } : {};
}
