/**
 * Intrinsic dimensions and responsive variants for every plate, generated by
 * produccion/edicion.py from the files themselves.
 *
 * Section 91. Without width/height the browser cannot reserve space and the
 * document reflowed as plates decoded; without srcset a 390px phone pulled a
 * 1680px plate whole. Typing either by hand would let them drift from the
 * assets the pipeline cuts, so both are read off the files.
 */
export const MEDIDAS: Record<string, readonly [number, number]> = {
  "/cine/a2-esmeralda.avif": [1200, 262],
  "/cine/a2-isabella.avif": [596, 842],
  "/cine/a2-raiz.avif": [1000, 812],
  "/cine/a2-vibe.avif": [385, 835],
  "/cine/a3-ingres.avif": [1200, 1020],
  "/cine/a3-lobo.avif": [613, 860],
  "/cine/a3-loreal.avif": [889, 944],
  "/cine/a4-ceguera.avif": [1400, 1400],
  "/cine/a4-pelo-plano.avif": [1500, 1500],
  "/cine/a4-pintura.avif": [1500, 1500],
  "/cine/pelo-cobre.avif": [1150, 3229],
  "/edicion/campana-marquesina-poster.avif": [1280, 1913],
  "/edicion/cap-impreso.avif": [1553, 1013],
  "/edicion/cap-marca.avif": [1680, 1260],
  "/edicion/cap-producto.avif": [1280, 796],
  "/edicion/ceguera-figura.avif": [1100, 1629],
  "/edicion/detalle-vibe.avif": [377, 542],
  "/edicion/detalle-voluntee.avif": [345, 412],
  "/edicion/estado-vibe-1.avif": [392, 854],
  "/edicion/estado-vibe-2.avif": [392, 854],
  "/edicion/estado-vibe-3.avif": [392, 854],
  "/edicion/estado-vibe-4.avif": [392, 854],
  "/edicion/hero-retablo-completo.avif": [1680, 1050],
  "/edicion/hero-retablo.avif": [1680, 1050],
  "/edicion/marca-raiz.avif": [900, 640],
  "/edicion/oficio-doc-cv-en.avif": [744, 1052],
  "/edicion/oficio-doc-cv-es.avif": [744, 1052],
  "/edicion/oficio-doc-grafico.avif": [744, 1052],
  "/edicion/oficio-retrato.avif": [900, 1350],
  "/edicion/panel-3.avif": [580, 1010],
  "/edicion/panel-6.avif": [310, 400],
  "/edicion/panel-7.avif": [360, 470],
  "/edicion/panel-9.avif": [240, 300],
  "/edicion/plancha-vibe.avif": [428, 3012],
  "/edicion/plancha-voluntee.avif": [375, 1471],
  "/edicion/plano-i-bg.avif": [1400, 1400],
  "/edicion/plano-i-fg.avif": [1200, 1200],
  "/edicion/plano-ii-bg.avif": [454, 484],
  "/edicion/plano-ii-fg.avif": [1400, 1050],
  "/edicion/plano-iii-bg.avif": [1400, 2092],
  "/edicion/plano-iv-bg.avif": [385, 835],
  "/edicion/plano-v-bg.avif": [860, 1209],
  "/edicion/plano-v-fg.avif": [1400, 913],
  "/images/about.png": [1024, 1536],
  "/images/asset4.png": [768, 202],
  "/images/luxeestate.png": [1024, 482],
  "/images/mockupisa.png": [4500, 3000],
  "/images/mockupraiz.png": [4000, 3000],
  "/images/portafolioabierto.png": [1553, 1013],
  "/images/profilepicture.png": [832, 1248],
  "/images/vibe.png": [1512, 982],
  "/images/voluntee.png": [2162, 1204],
  "/trabajo/t-esmeralda.avif": [900, 640],
  "/trabajo/t-ilustracion.avif": [900, 640],
  "/trabajo/t-isabella.avif": [900, 640],
  "/trabajo/t-libro.avif": [900, 640],
  "/trabajo/t-lobo.avif": [900, 640],
  "/trabajo/t-nespresso.avif": [900, 640],
  "/trabajo/t-vibe.avif": [900, 640],
  "/trabajo/t-voluntee.avif": [900, 640],
};

/** Narrow variants, widest last. Only cut for plates a phone would otherwise
 *  download at full size. */
const VARIANTES: Record<string, readonly (readonly [string, number])[]> = {
  "/edicion/campana-marquesina-poster.avif": [["/edicion/campana-marquesina-poster-w640.avif", 640], ["/edicion/campana-marquesina-poster-w1024.avif", 1024]],
  "/edicion/cap-impreso.avif": [["/edicion/cap-impreso-w640.avif", 640], ["/edicion/cap-impreso-w1024.avif", 1024]],
  "/edicion/cap-marca.avif": [["/edicion/cap-marca-w640.avif", 640], ["/edicion/cap-marca-w1024.avif", 1024]],
  "/edicion/cap-producto.avif": [["/edicion/cap-producto-w640.avif", 640], ["/edicion/cap-producto-w1024.avif", 1024]],
  "/edicion/ceguera-figura.avif": [["/edicion/ceguera-figura-w640.avif", 640], ["/edicion/ceguera-figura-w1024.avif", 1024]],
  "/edicion/hero-retablo-completo.avif": [["/edicion/hero-retablo-completo-w640.avif", 640], ["/edicion/hero-retablo-completo-w1024.avif", 1024]],
  "/edicion/hero-retablo.avif": [["/edicion/hero-retablo-w640.avif", 640], ["/edicion/hero-retablo-w1024.avif", 1024]],
  "/edicion/plano-i-bg.avif": [["/edicion/plano-i-bg-w640.avif", 640], ["/edicion/plano-i-bg-w1024.avif", 1024]],
  "/edicion/plano-i-fg.avif": [["/edicion/plano-i-fg-w640.avif", 640], ["/edicion/plano-i-fg-w1024.avif", 1024]],
  "/edicion/plano-ii-fg.avif": [["/edicion/plano-ii-fg-w640.avif", 640], ["/edicion/plano-ii-fg-w1024.avif", 1024]],
  "/edicion/plano-iii-bg.avif": [["/edicion/plano-iii-bg-w640.avif", 640], ["/edicion/plano-iii-bg-w1024.avif", 1024]],
  "/edicion/plano-v-fg.avif": [["/edicion/plano-v-fg-w640.avif", 640], ["/edicion/plano-v-fg-w1024.avif", 1024]],
};

/**
 * Props for an <img>: intrinsic size, plus srcset/sizes where variants exist.
 *
 * `sizes` defaults to the common case -- a full-bleed ground on a phone, half
 * the viewport on a desktop -- and callers override it where the element is
 * genuinely smaller. That override matters: `sizes` is a PROMISE to the
 * browser, and one that overstates makes it choose a larger file than it needs.
 * The hero anachronism displays at 172px on a phone and was claiming 100vw, so
 * it pulled the 1100px original every time.
 */
export function medidas(src: string, sizes = "(max-width: 767px) 100vw, 50vw") {
  const m = MEDIDAS[src];
  if (!m) return {};
  const v = VARIANTES[src];
  if (!v) return { width: m[0], height: m[1] };
  const srcSet = [...v.map(([s, w]) => `${s} ${w}w`), `${src} ${m[0]}w`].join(", ");
  return {
    width: m[0],
    height: m[1],
    srcSet,
    sizes,
  };
}
