import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by shadcn, never hand-edited. _shared/engineering/conventions.md
    // says to regenerate rather than patch these, so linting them produces
    // findings nobody is allowed to act on. Both files that failed here
    // (ui/carousel.tsx and the use-mobile hook it reaches through sidebar.tsx)
    // are also unused by the site.
    //
    // This does not hide problems in code we write: components/site/ and app/
    // are still linted in full.
    "components/ui/**",
    "hooks/use-mobile.ts",
  ]),
]);

export default eslintConfig;
