import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by shadcn, never hand-edited. conventions.md says to regenerate
    // rather than patch these, so linting them produces findings nobody is
    // allowed to act on. Both are also unused by the site.
    //
    // Scoped to the two files that actually fail. The previous pattern was
    // components/ui/**, which swallowed 61 files including dialog.tsx -- live
    // code on the flipbook journey, and the component MP-18 was reacting to.
    "components/ui/carousel.tsx",
    "hooks/use-mobile.ts",
  ]),
]);

export default eslintConfig;
